image: python

stages:
- test

before_script:
- curl -O https://bootstrap.pypa.io/get-pip.py
- python get-pip.py
- pip install -r dev-requirements.txt

python2:
  image: python:2.7
  stage: test
  script: tox -e py27

python34:
  image: python:3.4
  stage: test
  script: tox -e py34

python35:
  image: python:3.5
  stage: test
  script: tox -e py35

python36:
  image: python:3.6
  stage: test
  script: tox -e py36

python37:
  image: python:3.7
  stage: test
  script: tox -e py37

pypy:
  image: pypy:2
  stage: test
  script: tox -e pypy

pypy3:
  image: pypy:3
  stage: test
  script: tox -e pypy3

pylint:
  image: python:3.7
  stage: test
  script: tox -e pylint

pep8:
  stage: test
  script: tox -e pep8
