image: python

stages:
- earlytest
- fulltest
- deploy

before_script:
- curl -O https://bootstrap.pypa.io/get-pip.py
- python get-pip.py
- pip install -r dev-requirements.txt

pylint:
  image: python:3.7
  stage: earlytest
  script: tox -e pylint

pep8:
  stage: earlytest
  script: tox -e pep8

python2:
  image: python:2.7
  stage: earlytest
  script: tox -e py27

python3:
  image: python:3.7
  stage: earlytest
  script: tox -e py37

python34:
  image: python:3.4
  stage: fulltest
  script: tox -e py34

python35:
  image: python:3.5
  stage: fulltest
  script: tox -e py35

python36:
  image: python:3.6
  stage: fulltest
  script: tox -e py36

pythonrc:
  image: python:rc
  stage: fulltest
  script: tox -e py38

pypy:
  image: pypy:2
  stage: fulltest
  script: tox -e pypy

pypy3:
  image: pypy:3
  stage: fulltest
  script: tox -e pypy3

coveralls:
  image: python:3.7
  variables:
    CI_NAME: gitlab
    CI_BUILD_NUMBER: "${CI_JOB_ID}"
    CI_BUILD_URL: "${CI_JOB_URL}"
    CI_BRANCH: "${CI_COMMIT_REF_NAME}"
  stage: deploy
  script:
    - pip install coveralls
    - coverage run --source=cryptoparser setup.py test
    - coveralls
  only:
    refs:
      - master

obs:
  image: coroner/cryptolyzer:obs
  stage: deploy
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - obs.sh
  only:
    refs:
      - master
      - tags
