image: python

stages:
- earlytest
- fulltest
- deploy

before_script:
- pip install uv
- uv pip install --system .[tests]

variables:
  GIT_SUBMODULE_DEPTH: 1
  GIT_SUBMODULE_STRATEGY: recursive
  PYTHONPATH: "submodules/cryptodatahub"

.test:
  script:
  - coverage run -m unittest discover -v
  - coverage report

pylint:
  image: python:3.14-slim
  stage: earlytest
  script:
  - uv pip install --system pylint
  - pylint --rcfile .pylintrc cryptoparser docs test

ruff:
  image: python:3.14-slim
  stage: earlytest
  script: uvx ruff check cryptoparser docs test

python314:
  extends: .test
  image: python:3.14-slim
  stage: earlytest

python39:
  extends: .test
  image: python:3.9-slim
  stage: fulltest

python310:
  extends: .test
  image: python:3.10-slim
  stage: fulltest

python311:
  extends: .test
  image: python:3.11-slim
  stage: fulltest

python312:
  extends: .test
  image: python:3.12-slim
  stage: fulltest

python313:
  extends: .test
  image: python:3.13-slim
  stage: fulltest

pythonrc:
  extends: .test
  image: python:3.15-rc-slim
  stage: fulltest

pypy3:
  extends: .test
  image: pypy:3-slim
  stage: fulltest

coveralls:
  image: python:3.12-slim
  variables:
    CI_NAME: gitlab
    CI_BUILD_NUMBER: "${CI_JOB_ID}"
    CI_BUILD_URL: "${CI_JOB_URL}"
    CI_BRANCH: "${CI_COMMIT_REF_NAME}"
    GIT_SUBMODULE_DEPTH: 1
    GIT_SUBMODULE_STRATEGY: recursive
    PYTHONPATH: "submodules/cryptodatahub"
  stage: deploy
  script:
    - uv pip install --system coveralls
    - coverage run -m unittest -v -f
    - coveralls
  only:
    refs:
      - master

obs:
  image:
    name: coroner/python_obs:1.2.5
    pull_policy: always
  stage: deploy
  variables:
    GIT_SUBMODULE_DEPTH: 1
    GIT_SUBMODULE_STRATEGY: recursive
  before_script: []
  script:
    - obs.sh
  only:
    refs:
      - master
      - tags
