image: python

stages:
- earlytest
- fulltest
- deploy

before_script:
- pip install -r dev-requirements.txt

pylint:
  image: python:3.7-slim
  stage: earlytest
  script: tox -e pylint

pep8:
  stage: earlytest
  script: tox -e pep8

python2:
  image: python:2.7-slim
  stage: earlytest
  script: tox -e py27

python3:
  image: python:3.7-slim
  stage: earlytest
  script: tox -e py37

python34:
  image: python:3.4-slim
  stage: fulltest
  script: tox -e py34

python35:
  image: python:3.5-slim
  stage: fulltest
  script: tox -e py35

python36:
  image: python:3.6-slim
  stage: fulltest
  script: tox -e py36

python38:
  image: python:3.8-slim
  stage: fulltest
  script: tox -e py38

python39:
  image: python:3.9-slim
  stage: fulltest
  script: tox -e py39

python310:
  image: python:3.10-slim
  stage: fulltest
  script: tox -e py310

pythonrc:
  image: python:3.11-rc-slim
  stage: fulltest
  script: tox -e py311

pypy:
  image: pypy:2-slim
  stage: fulltest
  script: tox -e pypy

pypy3:
  image: pypy:3-slim
  stage: fulltest
  script: tox -e pypy3

coveralls:
  image: python:3.7
  variables:
    CI_NAME: gitlab
    CI_BUILD_NUMBER: "${CI_JOB_ID}"
    CI_BUILD_URL: "${CI_JOB_URL}"
    CI_BRANCH: "${CI_COMMIT_REF_NAME}"
  stage: deploy
  script:
    - pip install coveralls
    - coverage run --source=cryptoparser setup.py test
    - coveralls
  only:
    refs:
      - master

obs:
  image: coroner/cryptolyzer:obs
  stage: deploy
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - obs.sh
  only:
    refs:
      - master
      - tags
